export const WORDS = [
  'o', 'a', 'e', 'de', 'do', 'da', 'em', 'um', 'para', 'com',
  'não', 'uma', 'os', 'no', 'se', 'na', 'por', 'mais', 'as', 'dos',
  'como', 'mas', 'foi', 'ao', 'ele', 'das', 'tem', 'à', 'seu', 'sua',
  'quando', 'muito', 'há', 'nos', 'já', 'está', 'eu', 'também', 'só', 'pelo',
  'pela', 'até', 'isso', 'ela', 'entre', 'era', 'depois', 'sem', 'mesmo', 'aos',
  'ter', 'seus', 'quem', 'nas', 'me', 'esse', 'eles', 'estão', 'você', 'tinha',
  'foram', 'essa', 'num', 'nem', 'suas', 'meu', 'às', 'minha', 'têm', 'numa',
  'pelos', 'elas', 'havia', 'seja', 'qual', 'será', 'nós', 'tenho', 'lhe', 'deles',
  'essas', 'esses', 'pelas', 'este', 'fosse', 'dele', 'tu', 'te', 'vocês', 'vos',
  'lhes', 'meus', 'minhas', 'teu', 'tua', 'teus', 'tuas', 'nosso', 'nossa', 'nossos',
  'nossas', 'dela', 'delas', 'esta', 'estes', 'estas', 'aquele', 'aquela', 'aqueles', 'aquelas',
  'casa', 'tempo', 'ano', 'dia', 'vida', 'homem', 'mulher', 'mundo', 'país', 'cidade',
  'trabalho', 'dinheiro', 'amor', 'amigo', 'família', 'criança', 'pessoa', 'lugar', 'hora', 'mês',
  'semana', 'minuto', 'segundo', 'cor', 'azul', 'vermelho', 'verde', 'amarelo', 'preto', 'branco',
  'grande', 'pequeno', 'alto', 'baixo', 'bom', 'mau', 'novo', 'velho', 'primeiro', 'último',
  'melhor', 'pior', 'rápido', 'lento', 'fácil', 'difícil', 'certo', 'errado', 'feliz', 'triste',
  'rico', 'pobre', 'jovem', 'velho', 'forte', 'fraco', 'doce', 'azedo', 'quente', 'frio',
  'limpo', 'sujo', 'cheio', 'vazio', 'aberto', 'fechado', 'livre', 'ocupado', 'pronto', 'ocupado',
  'importante', 'necessário', 'possível', 'impossível', 'verdadeiro', 'falso', 'real', 'falso', 'certo', 'errado',
  'escola', 'professor', 'aluno', 'livro', 'papel', 'caneta', 'mesa', 'cadeira', 'porta', 'janela',
  'carro', 'ônibus', 'trem', 'avião', 'navio', 'bicicleta', 'estrada', 'rua', 'ponte', 'rio',
  'mar', 'oceano', 'montanha', 'floresta', 'árvore', 'flor', 'grama', 'sol', 'lua', 'estrela',
  'chuva', 'vento', 'nuvem', 'neve', 'fogo', 'água', 'terra', 'ar', 'comida', 'bebida',
  'pão', 'arroz', 'carne', 'peixe', 'fruta', 'legume', 'sopa', 'salada', 'café', 'chá',
  'leite', 'suco', 'cerveja', 'vinho', 'doce', 'bolo', 'sorvete', 'chocolate', 'queijo', 'manteiga'
];
